name: phpcs

on:
  push:
    paths:
      - 'src/**.php'
      - 'tests/**.php'
      - 'phpcs.xml.dist'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    name: phpcs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute phpcs
        run: composer lint
